version: '3.3'

services:
  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./storage/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  redis:
    image: redis:5-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./storage/redis:/data
    command: 'redis-server --appendonly yes'

  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - ./storage/rabbitmq/etc/:/etc/rabbitmq/
      - ./storage/rabbitmq/data/:/var/lib/rabbitmq/
      - ./storage/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 5672:5672
      - 15672:15672

  app:
    build: .
    image: go-boilerplate:latest
    depends_on:
      - mongo
      - redis
    volumes:
      - ./example.config.yaml:/etc/go-boilerplate/app.config.yaml
    ports:
      - 8080:8080
      - 3550:3550
    command: 'serve-grpc-rest --config /etc/go-boilerplate/app.config.yaml'

  worker:
    image: go-boilerplate:latest
    depends_on:
      - mongo
      - redis
      - rabbitmq
    restart: on-failure
    volumes:
      - ./example.config.yaml:/etc/go-boilerplate/app.config.yaml
    command: 'consumer --config /etc/go-boilerplate/app.config.yaml'

