// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: proto/brand.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ListBrandReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListBrandReq) Reset() {
	*x = ListBrandReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_brand_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBrandReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBrandReq) ProtoMessage() {}

func (x *ListBrandReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brand_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBrandReq.ProtoReflect.Descriptor instead.
func (*ListBrandReq) Descriptor() ([]byte, []int) {
	return file_proto_brand_proto_rawDescGZIP(), []int{0}
}

type ListBrandRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brands []*Brand `protobuf:"bytes,1,rep,name=brands,proto3" json:"brands,omitempty"`
}

func (x *ListBrandRes) Reset() {
	*x = ListBrandRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_brand_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBrandRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBrandRes) ProtoMessage() {}

func (x *ListBrandRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brand_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBrandRes.ProtoReflect.Descriptor instead.
func (*ListBrandRes) Descriptor() ([]byte, []int) {
	return file_proto_brand_proto_rawDescGZIP(), []int{1}
}

func (x *ListBrandRes) GetBrands() []*Brand {
	if x != nil {
		return x.Brands
	}
	return nil
}

type Brand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                    int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	InvoiceNumber         string `protobuf:"bytes,2,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	Customer              string `protobuf:"bytes,4,opt,name=customer,proto3" json:"customer,omitempty"`
	Quantity              int32  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ShopItemId            int32  `protobuf:"varint,8,opt,name=shop_item_id,json=shopItemId,proto3" json:"shop_item_id,omitempty"`
	Status                string `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	CustomerContactNumber string `protobuf:"bytes,13,opt,name=customer_contact_number,json=customerContactNumber,proto3" json:"customer_contact_number,omitempty"`
}

func (x *Brand) Reset() {
	*x = Brand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_brand_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Brand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Brand) ProtoMessage() {}

func (x *Brand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brand_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Brand.ProtoReflect.Descriptor instead.
func (*Brand) Descriptor() ([]byte, []int) {
	return file_proto_brand_proto_rawDescGZIP(), []int{2}
}

func (x *Brand) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Brand) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

func (x *Brand) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *Brand) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Brand) GetShopItemId() int32 {
	if x != nil {
		return x.ShopItemId
	}
	return 0
}

func (x *Brand) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Brand) GetCustomerContactNumber() string {
	if x != nil {
		return x.CustomerContactNumber
	}
	return ""
}

var File_proto_brand_proto protoreflect.FileDescriptor

var file_proto_brand_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x22, 0x0e, 0x0a,
	0x0c, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x22, 0x37, 0x0a,
	0x0c, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x12, 0x27, 0x0a,
	0x06, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x62, 0x72, 0x61, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x52, 0x06,
	0x62, 0x72, 0x61, 0x6e, 0x64, 0x73, 0x22, 0xe8, 0x01, 0x0a, 0x05, 0x42, 0x72, 0x61, 0x6e, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12,
	0x20, 0x0a, 0x0c, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x36, 0x0a, 0x17, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x32, 0x4d, 0x0a, 0x0c, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3d, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x16,
	0x2e, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x72,
	0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_brand_proto_rawDescOnce sync.Once
	file_proto_brand_proto_rawDescData = file_proto_brand_proto_rawDesc
)

func file_proto_brand_proto_rawDescGZIP() []byte {
	file_proto_brand_proto_rawDescOnce.Do(func() {
		file_proto_brand_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_brand_proto_rawDescData)
	})
	return file_proto_brand_proto_rawDescData
}

var file_proto_brand_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_brand_proto_goTypes = []interface{}{
	(*ListBrandReq)(nil), // 0: brand.v1.ListBrandReq
	(*ListBrandRes)(nil), // 1: brand.v1.ListBrandRes
	(*Brand)(nil),        // 2: brand.v1.Brand
}
var file_proto_brand_proto_depIdxs = []int32{
	2, // 0: brand.v1.ListBrandRes.brands:type_name -> brand.v1.Brand
	0, // 1: brand.v1.BrandService.ListBrand:input_type -> brand.v1.ListBrandReq
	1, // 2: brand.v1.BrandService.ListBrand:output_type -> brand.v1.ListBrandRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_brand_proto_init() }
func file_proto_brand_proto_init() {
	if File_proto_brand_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_brand_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBrandReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_brand_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBrandRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_brand_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Brand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_brand_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_brand_proto_goTypes,
		DependencyIndexes: file_proto_brand_proto_depIdxs,
		MessageInfos:      file_proto_brand_proto_msgTypes,
	}.Build()
	File_proto_brand_proto = out.File
	file_proto_brand_proto_rawDesc = nil
	file_proto_brand_proto_goTypes = nil
	file_proto_brand_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BrandServiceClient is the client API for BrandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BrandServiceClient interface {
	ListBrand(ctx context.Context, in *ListBrandReq, opts ...grpc.CallOption) (*ListBrandRes, error)
}

type brandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrandServiceClient(cc grpc.ClientConnInterface) BrandServiceClient {
	return &brandServiceClient{cc}
}

func (c *brandServiceClient) ListBrand(ctx context.Context, in *ListBrandReq, opts ...grpc.CallOption) (*ListBrandRes, error) {
	out := new(ListBrandRes)
	err := c.cc.Invoke(ctx, "/brand.v1.BrandService/ListBrand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrandServiceServer is the server API for BrandService service.
type BrandServiceServer interface {
	ListBrand(context.Context, *ListBrandReq) (*ListBrandRes, error)
}

// UnimplementedBrandServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBrandServiceServer struct {
}

func (*UnimplementedBrandServiceServer) ListBrand(context.Context, *ListBrandReq) (*ListBrandRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBrand not implemented")
}

func RegisterBrandServiceServer(s *grpc.Server, srv BrandServiceServer) {
	s.RegisterService(&_BrandService_serviceDesc, srv)
}

func _BrandService_ListBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBrandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrandServiceServer).ListBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/brand.v1.BrandService/ListBrand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrandServiceServer).ListBrand(ctx, req.(*ListBrandReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _BrandService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "brand.v1.BrandService",
	HandlerType: (*BrandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBrand",
			Handler:    _BrandService_ListBrand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/brand.proto",
}
